mparticle-integrations/mparticle-apple-integration-appboy

- mParticle-Appboy.podspec
- mParticle-Appboy/MPKitAppboy.m
The `forwardScreenViews` flag indicates whether `logScreen` should be forwarded to Appboy. It defaults to `NO`.
> Forward screen configuration flag

- mParticle-Appboy/MPKitAppboy.m
The kit protocol method for 'setUserAttribute: values' was not implemented. Therefor there was no way to call the appropriate Braze method 'setCustomAttributeArrayWithKey:array:' for user Attributes that are lists.
Build compiled. Ran local testing.
> Update Appboy to Allow Custom Attribute Lists

- mParticle-Appboy/MPKitAppboy.m
This PR makes it so that if the Braze SDK is disabled prior to mParticle's SDK start, it will not be added as an active kit and won't crash on the line immediately after this.
That said - I think a more comprehensive change would account for the Braze SDK being disable at any time. I believe the Braze kit today maintains a reference to Braze's instance due to a long-past bug in the Braze SDK and should likely be refactored to de-initialize or just otherwise release the reference and not crash if a customer called the `disable` API at any moment.
> Prevent possible crash if braze sdk is disabled

- mParticle-Appboy/MPKitAppboy.m
Problem:
While attempting to leverage inAppMessageControllerDelegate, I noticed I was not able to get Delegate Callbacks.
Investigation:
Noticed that although a static member was declared for inAppMessageControllerDelegate, this value was never used
Change:
If the static delegate member is set before the SharedInstance is initialized, pass into iVar delegate.
There's likely many more optimizations to support changing. As well as updating the delegate to be weak instead of strong? But wanted to get the ball rolling on this with eyes that are more aware of the models/functionality (honestly even objc styling here)
> Support InAppMessageControllerDelegate

- mParticle-Appboy/MPKitAppboy.m
Currently there is no way to set gender in Braze kit as anything other than ABKUserGenderMale and ABKUserGenderFemale. We should allow the user to set ABKUserGenderNotApplicable and also not default to Female.
If gender is set to something that is not an mParticle gender enum then
default to ABKUserGenderOther
> Allow Braze kit to set mParticleGenderNotAvailable

- mParticle-Appboy/MPKitAppboy.m
- mParticle_AppboyTests/mParticle_AppboyTests.m
Braze has updated their ABKAppboyEndpointDelegate and the format of their associated endpoint URL. This change update the kit to treat the url in the same way that Braze performs it. https://github.com/Appboy/appboy-ios-sdk/blob/master/Example/Stopwatch/OverrideEndpointDelegate.m
> Update Endpoint Override

- .travis.yml
- mParticle-Appboy/MPKitAppboy.m
- mParticle_AppboyTests/mParticle_AppboyTests.m
Walking through the code in my test app I confirmed that in the Braze Kit we are not checking what the External Identity Type is when setting the Braze User customer Id.
> Respect UserIdentificationType in KitConfig

- Cartfile
This is necessary because the version of the Appboy SDK specified by the manifest file does not include their UI libraries.
> Use non-binary appboy dependency

- .github/workflows/verify.yml
- mParticle-Appboy/MPKitAppboy.m
If the Braze kit has been initialized already, there's no reason to *not* mark it as started. This resolves an issue for customers who are late-initializing mParticle and Braze is missing the launch notification.
> Start the kit early if Braze has been initialized

- mParticle-Appboy/MPKitAppboy.m
The Braze Web SDK lets you set a ABKURLDelegate delegate during initialization of their SDK such that you can customize how their SDK handles URLs for pushes.
These are Braze docs on it: https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/advanced_use_cases/linking/#linking-handling-customization
This exposes a setter such that a customer can statically set their own delegate on the kit, prior to initializing our SDK.
> Support ABKURLDelegate

- mParticle-Appboy/MPKitAppboy.m
- mParticle_AppboyTests/mParticle_AppboyTests.m
Note that detection for user attributes, which previously always took place,
now happens only when the 'enableTypeDetection' connection setting is true
> Add type detection for BOOLs, custom event attrs

- mParticle-Appboy.podspec
Due to the architecture changes of simulators in Xcode 12, this change needs to be made to the mParticle-Braze SDK podspec.
> Update podspec for Xcode 12

- mParticle-Appboy/MPKitAppboy.m
A configuration for determining which identity to use for email in the braze kit was added to our configuration settings server side. This change brings support for that feature to the iOS SDK.
> Add Email Identity Type Support

- mParticle-Appboy.podspec
This removes the excluded architecture setting from being set by both `s.` and `s.{ios,tvos}.`
> Fix duplicate excluded archs settings

- mParticle-Appboy/MPKitAppboy.m
The '-Started' flag was not being set on 'start' after consent disables and then reenables a kit.  This was occurring because start was being done within a dispatch once which was only supposed to contain the setup for the kit sdk.
> Allow Start to Set Flag on Reactivation

- Package.swift
There have been some issues regarding the Appboy git URL cloning ~1.4GB of data when using the AppBoy link with SPM. 
More info:
https://github.com/Appboy/appboy-ios-sdk/issues/289
https://github.com/Appboy/appboy-segment-ios/pull/56
[Braze documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/initial_sdk_setup/installation_methods/swift_package_manager/?redirected=true#step-1-adding-the-dependency-to-your-project) also recommends using  https://github.com/braze-inc/braze-ios-sdk.
> Update SPM SDK package to use braze url instead of AppBoy

- Sources/mParticle-Appboy/MPKitAppboy.m
Summary
Food Truck Inc. has reported that when they use our reserved zipcode attribute it gets converted to a number/integer due to enabling the datatype detection in which is needed for other non-reserved attributes. This results in some zipcodes appearing wrong in some cases (for example: inputting "07090" as a zipcode would be forwarded to Braze as 7090).
Testing Plan
Tested the reserved zipcodes both if entered as a string value or a numeric value. Works fine on both where in the case of numeric values it would be stringified (in the case for some reason clients were passing reserved zipcode attribute as an integer).
Note: same issue relevant in Android and PR coming to the Appboy Android kit soon as well :)
> fix: prevent converting stringified zipcode to integer

- Sources/mParticle-Appboy/include/mParticle_Appboy.h
While trying to import the package into one of their swift files a developer was getting the following error "Could not build objective-c module mParticle_Adobe".
Tested through targeting this branch with SPM in in swift example app.
> fix: fix spm imports

- Cartfile
- Package.swift
- Sources/mParticle-Appboy/MPKitAppboy.m
Starting with the Braze iOS SDK [4.4.0](https://github.com/Appboy/appboy-ios-sdk/blob/master/CHANGELOG.md#440), Braze can now track metadata about the integration method.
This PR marks mParticle integration with the appropriate SDK metadata, it also raises the minimum Braze iOS SDK to `4.4.0` to ensure that this feature is available.
> Add SDK Metadata

- Package.swift
- Sources/mParticle-Appboy/MPKitAppboy.m
Make `Package.swift` great again
Basically, the package is broken, and it can't be included in the project as dependencies can't resolve correctly. Another issues is that after that fix it is possible to include the package, but it doesn't compile because of errors inside of `braze-swift-sdk`
- Just try to add the latest version of the SDK into the test project
> Fix: Package.swift

- Sources/mParticle-Appboy/MPKitAppboy.m
Noticed this happening in `v8.1.1` after testing out #71.
NSNull user email was not being filtered by the **if (userEmail)** in `updateUser`. 
So `appboyInstance.user.setEmail` was being called with that NSNull object. But it expects an NSString, triggering an `unrecognized selector sent to instance` error.
- Only tested with a local app. I tried to create a new test but I wasn't able to instantiate an `MPKitConfiguration` for some reason.
> fix: Crash when anonymous users return an NSNull email

- Package.swift
- SPM/mParticle-Appboy-NoLocation
- Sources/mParticle-Appboy/include/MPKitAppboy.h
- Sources/mParticle-Appboy/include/mParticle_Appboy.h
Add dedicated NoLocation target to SPM with a dependency on the NoLocation version of the mParticle SDK. This prevents the issue where a customer adds the NoLocation SDK and then the kit depends on the standard version, which causes both to be included.
- Confirmed in a test app that both targets work as expected
- Closes https://go.mparticle.com/work/SQDSDKS-5439
> feat: Add NoLocation target to SPM

- Sources/mParticle-Appboy/MPKitAppboy.m
- mParticle-Appboy.podspec
- mParticle_AppboyTests/mParticle_AppboyTests.m
1. All commerce events (both purchase and non-purchase events) forwarded to Braze as a single event with products nested in event properties when forwardEnhancedECommerceData set to true.
2. All commerce events (both purchase and non-purchase events) forwarded to Braze as expanded individual events for each product when forwardEnhancedECommerceData set to false.
- Tested manualy
- Closes https://go.mparticle.com/work/SQDSDKS-5427
> feat: add order level commerce events

- Sources/mParticle-Appboy/MPKitAppboy.m
- multiple customers have mentioned that Braze in app messages stopped working since version 8.1.0 when we started utilizing the newer Braze swift SDK, after further investigation it seems that we were missing the line to include the inAppMessagePresenter.
- [Y] Was this tested locally? If not, explain why.
- Tested locally with firing a dummy inAppMessage from Braze to my iOS simulator
- Closes https://mparticle-eng.atlassian.net/browse/PRODRDMP-5617
> fix: in app message display fix for new Braze swift kit

- Sources/mParticle-Appboy/MPKitAppboy.m
- mParticle-Appboy.xcodeproj/project.pbxproj
- mParticle_AppboyTests/mParticle_AppboyTests.m
- This PR Fixes the bundleCommerceEventData config that was placed in the function that send the data to Braze, which override the current setting for the connection that can be seen in the UI.
- Test for unbundled data are also fixed by setting the bundleCommerceEventData config explicitly to false on.
- VALID_ARCHS setting within the project is modified to avoid a build issue for M1+ Macs.
- [Y] Was this tested locally? If not, explain why.
- Test performed manually in addition to fixing the unit tests. Previously, only bundled data could be seen in Braze's dashboard. Now the config via mParticle UI is taken into account.
Unbundled data in Braze:
Bundled data in Braze:
- Closes https://mparticle-eng.atlassian.net/browse/SQDSDKS-5916
> Fix: bundle commerce event setting

- Sources/mParticle-Appboy/include/MPKitAppboy.h
- MPIHasher was updated to a Swift class which required the umbrella header to imported rather than the old public header when not doing the module import. The majority of kits don't use MPIHasher so they aren't affected though we have created tickets to update them in the future.
- Confirmed compilation and build then manually tested MPIHasher functionality once imported correctly
- Closes https://go.mparticle.com/work/PRODRDMP-6099
> fix: Use Umbrella Imports

- Sources/mParticle-Appboy/MPKitAppboy.m
- mParticle_AppboyTests/mParticle_AppboyTests.m
1. PR target branch should be against `development`
2. PR title name should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-title-check.yml
3. PR branch prefix should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-branch-check-name.yml
- This PR allows sending the product name, category and affiliation when sending each product separately for a purchase event. I've modified the associated test as well.
It was tested manually by checking the payloads that braze receives.
This is a sample payload of a product with category without the change:
This is a sample payload with the change:
> fix: Deleting property stripping from product when sent unbundled

- Sources/mParticle-Appboy/MPKitAppboy.m
- Sources/mParticle-Appboy/include/MPKitAppboy.h
- mParticle_AppboyTests/mParticle_AppboyTests.m
Due to the partner SDK changes (from Appboy to Braze) the implementation changed a bit and the kit was no longer to fully handle attribution to Braze for notifications that open the app (cold start).
These changes allow customers to inform the kit that they will handle notifications in their app code as well as allowing them to set their own braze instance to the kit (which is required to handle notifications manually).
Docs updates will be forthcoming. 
- Heavily tested pairing with Michael G
- Closes https://go.mparticle.com/work/SQDSDKS-6148
> feat: Allow setting Braze instance and override notification handling

- Package.swift
- Sources/mParticle-Appboy/MPKitAppboy.m
- Sources/mParticle-Appboy/PrivacyInfo.xcprivacy
- Sources/mParticle-Appboy/include/MPKitAppboy.h
- mParticle-Appboy.podspec
- mParticle-Appboy.xcodeproj/project.pbxproj
- Updates Braze dependency to 9.x.x (required for privacy manifest changes)
- Adds some new kit functionality to use the new Braze changes (will update docs tomorrow)
- Fixed some new Swift warnings (errors?) around configuration parameters (that's why there's some more changes here than would seem necessary)
- E2E event smoke test up to Braze
- Tested setting the tracking allow list from both a Swift and Obj-C app
- Tested generating privacy reports using all three package managers
- Closes https://go.mparticle.com/work/SQDSDKS-6405
> feat: Update to Braze 9.x.x SDK, improve privacy manifest support

- Sources/mParticle-Appboy/MPKitAppboy.m
- mParticle_AppboyTests/mParticle_AppboyTests.m
- We had a class method to set a Braze delegate, but it ultimately wasn't being set on the instance. This resolves that issue.
- Also I made all delegates strong references as they're static anyway and weak can cause potential issues between setting and using depending on how the customer stores the reference.
- Confirmed with breakpoints that it is correctly being set now.
- Closes https://go.mparticle.com/work/SQDSDKS-6502
> fix: Setting urlDelegate on Braze instance

- Sources/mParticle-Appboy/MPKitAppboy.m
- To better serve customer data product requested we update the external id on app launch
- Tested on sample app
- Closes https://go.mparticle.com/work/SQDSDKS-6494
> feat: Update External iD on Initialization

- Sources/mParticle-Appboy/MPKitAppboy.m
The change allows the kit to set if the screen events should be forwarded to Braze using the mP config data when the Braze Instance is initialized externally and then set as the appboy kit instance.
I tested it manually.
Before the change:
After the change:
> fix: add forward screen events config when using an external Braze instance

- Sources/mParticle-Appboy/include/MPKitAppboy.h
Confirmed working now in test app, tested event flow to kit and confirmed the kitApi property has a value.
> fix: Kit fails to start due to missing kitApi property

- Sources/mParticle-Appboy/MPKitAppboy.m
- mParticle-Appboy.podspec
- Update to latest version of Braze and implement collection of consent states
- Tested on QA1
- Closes https://go.mparticle.com/work/SQDSDKS-6387
> feat: Implement Google EU Consent

- Package.swift
- Updated SPM to use latest version of Braze
- Confirmed locally
- Closes https://go.mparticle.com/work/REPLACEME
> fix: update Braze Version for SPM

- Sources/mParticle-Appboy/MPKitAppboy.m
1. PR target branch should be against `development`
2. PR title name should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-title-check.yml
3. PR branch prefix should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-branch-check-name.yml
- The `updateConsent` is now called after the kit is initialized so that the mapping of the consent attributes is done correctly with an active kit.
- Set a breakpoint in the mapping of the consent attributes to evaluate the status of the kit (NOT nil)
- Closes https://go.mparticle.com/work/SQDSDKS-6864
> fix: Update Consent When Kit Is Initialized

- Sources/mParticle-Appboy/MPKitAppboy.m
- mParticle_AppboyTests/mParticle_AppboyTests.m
- Added a check for the optional flag to send product name rather than sku
- Tested with QA on simulator and added unit test
- Closes https://go.mparticle.com/work/SQDSDKS-6887
> feat: Add SendProductName Option to Braze

- Package.swift
- mParticle-Appboy.podspec
Braze informed us that versions 11.0 and 11.1 have a critical bug and requested that we raise our minimum dependency version to 11.2.
Note that we were already pinned up to next major, so version 11.2 and above would be pulled in automatically when updating, so this is just an extra precaution.
Smoke tested in both a CocoaPods and SPM project and ran `pod lib lint` locally to confirm the podspec.
- Closes https://go.mparticle.com/work/SQDSDKS-6931
> fix: Bump min Braze SDK to 11.2

- Sources/mParticle-Appboy/MPKitAppboy.m
- Use new server setting rather than webs
- Tested in simulator
- Closes https://go.mparticle.com/work/SQDSDKS-6887
> feat: Use replaceSkuWithProductName

- Sources/mParticle-Appboy/MPKitAppboy.m
- mParticle_AppboyTests/mParticle_AppboyTests.m
- Same summary as this [PR](https://github.com/mparticle-integrations/mparticle-apple-integration-appboy/pull/67) that haven't been merged, however the code on that PR is deprecated and this PR includes the new correct code
- E2E and Unit tested
- Closes https://go.mparticle.com/work/SQDSDKS-7111
> fix: Users attributes email and push subscribe mapping

- Package.swift
- mParticle-Appboy.podspec
- From Braze: Hi mParticle! We recently released an important fix in Braze Swift SDK 11.6.1 that impacts how Braze handles iCloud restore. Could we ask that you bump your integration to (preferably) Braze Swift SDK version 11.9.0, or at least 11.6.1 please?
- E2E tested
- Closes https://go.mparticle.com/work/SQDSDKS-7173
> fix: Update Braze to 11.9 to include iCloud restore fix

- Sources/mParticle-Appboy/MPKitAppboy.m
- mParticle_AppboyTests/mParticle_AppboyTests.m
- We currently support forwarding subscriptionGroupIds mapped via user attributes in our Braze S2S forwarder only, a customer mentioned that Braze support this feature in their Braze and requested this as a feature to our kits, refer to our [docs](https://docs.mparticle.com/integrations/braze/event/#subscription-groups) regarding subscription group ids
- E2E and unit tested
- Closes https://go.mparticle.com/work/SQDSDKS-7211
> feat: Add support to forward SubscriptionGroupIds
